version: '3.8'
services:
  app:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
